### PR TITLE
Qt6 support

### PR DESCRIPTION
**Pull request by ssakone**
### Migration to Qt6
*(CMAKE & QMAKE)*
#34 

I start migrating some functionality to Qt6

- [x] Apk information (👍 
- [x] Baterry State (👍 )
- [x] System information (👍)
- [x] Notification (⚠️  Partial done)
- [x] Sharing (⚠️  Partial done)
- [ ] App permission
- [ ] Expansion files
- [x] Screen  (👍 )
- [x] Signal strength
- [x] Images (👍 )
- [ ] ADMOB Banner
- [ ] ADMOB Intersititial
- [ ] ADMOB Rewarded Video
- [ ] Play Store
- [ ] Google Account
- [ ] Goole Drive
- [ ] User messaging platform
- [ ] Audio

### CODE REVIEW

**Comment by ssakone** [comment]
@FalsinSoft, I can addd more functionnality but the way will change lot of code, because Qt remove some essential element and now to done it i need to create another Java activity and make Qt use it to receive activity result.

**Comment by FalsinSoft** [comment]
@ssakone it's the reasons I still want to wait to do the porting. Qt 6 for Android are not complete and new changes can come out. Based to what I read  some "stable" configuration should be from version 6.4 (but not sure yet)

**Comment by ssakone** [comment]
> @ssakone it's the reasons I still want to wait to do the porting. Qt 6 for Android are not complete and new changes can come out. Based to what I read some "stable" configuration should be from version 6.4 (but not sure yet)

i already check the current progress of Qt6.4 but no big progress on it. i think i can hold little more Qt,

**Comment by FalsinSoft** [comment]
> i already check the current progress of Qt6.4 but no big progress on it. i think i can hold little more Qt,

Well, main problem is Qt teams still must to decide how to manage Android permissions request. Currently doesn't seems they have a clear idea about the API to implement and we need to wait for it right now. Another big issue they must to face are the new scoped storage of Android 11 and above. This will be a quite big issue to "fix"...

**Comment by ssakone** [comment]
@FalsinSoft https://www.qt.io/blog/unstringifying-android-development-with-qt-6.4 
i think they will not add more new thing.

**Comment by FalsinSoft** [comment]
It confirm what I said before. It's too early to start the porting because they still can change some "critical" part like the JNI interface. Maybe from 6.4 version the situation will became more stable...

**Comment by FalsinSoft** [comment]
Hi
Just pulled the version working with Qt 6.4.1. Unfortunately I needed to use the temporary solution by importing core-private because Qt teams seems very slow to develop "final" solution to support some Android features like permission and handle of activity event. This mean library are going to change again when final solution will be available. I didn't like this solution but, as already said, it seems Android features support is not a priority for Qt team right now...

**Pull request closed without merging**
